GET http://localhost:5000/api/valuation?apiKey=bshWIEe2dQV1avsY3uCgwpnBh2HHbOQAaxaTQxWa&osoite=Vilhonvuorenkatu%2012&kerros=1&parveke=1&kunta=Helsinki&kerros_yht=6&tonttiala=1&postinumero=00500&kunto=Hyv%C3%A4&muu_kerrosala=1&asuntotyyppi=Kerrostalo&tontti=vuokra&created_on=12.12.2020&asuinala=50&vastike=500&user=1&rakennusvuosi=2020&vuokrattu=1&huone_lkm=1&hissi=1&query_id=F93KJN2185&sauna=1
Content-Type: application/json

